export interface IExceptionTripReportResponseInterface{
    id: string;
    tripStartKm: number;
    tripEndKm: number;
    tripStartTime: number;
    tripEndTime: number;
    tripMaxSpeed: number;
    tripAvgSpeed: number;
    tripActualStartKm: number;
    tripActualEndKm: number;
    tripActualStartTime: number;
    tripActualEndTime: number;
    distanceCoverTrip: number;
    tripDistanceTobeCoverKm: number;
    distanceCoverPoint: number;
    reportOfTheDay: number;
    deviceStartTime: number;
    deviceOffTime: number;
    deviceOnTrackStartTime: number;
    deviceOffTrackStartTime: number;
    deviceImei: number;
    deviceName: string;
    deviceLocationCount: number;
    deviceLocationOnTrackCount: number;
    deviceTripStartBatteryStatus: number;
    deviceTripEndBatteryStatus: number;
    remark: string;
    tripNo: number;
}