name: Primesys Admin Build and Deploy


on:
    push:
        branches:
            - main


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code from Github Repository
              uses: actions/checkout@v4

            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                node-version: '24'
                cache: 'npm'

            - name: Install Dependencies and Build Project React
              run: |
                npm ci
                npm run build

            - name: Debug secrets
              run: |
                echo "SERVER_IP=${{ secrets.SERVER_IP != '' }}"
                echo "USERNAME=${{ secrets.USERNAME != '' }}"
                echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY != '' }}"
              
              

            - name: Deploy Compiled Files to VPS via Rsync
              uses: easingthemes/ssh-deploy@v5.1.0
              env:
                DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}

                ARGS: "-rltgoDz0 --delete"

                SERVER_PORT: "22"

                FOLDER: dist/

                SERVER_IP: ${{secrets.SERVER_IP}}

                USERNAME: ${{secrets.USERNAME}}

                SERVER_DESTINATION: "/var/www/html/mykidtracker"